#!/bin/sh -e
# shellcheck disable=2034,2091,3010,3037,3060 shell=busybox
# Custom UCI defaults script for Linksys MX4200/4300/5300 etc
# Create folder "files/etc/uci-defaults/" in build root and copy this script there.
# Customize to your needs.

# Uncomment the following line to capture all output to a log file
exec > /root/uci-defaults.log 2>&1

uci batch <<- EOF

# Set system options
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'

# Wireless default settings for radio0
set wireless.default_radio0.wnm_sleep_mode='1'
set wireless.default_radio0.ieee80211k='1'
set wireless.default_radio0.time_advertisement='2'
set wireless.default_radio0.bss_transition='1'
set wireless.default_radio0.proxy_arp='1'

# Wireless radio0 specific settings
set wireless.radio0.htmode='HE80'
set wireless.radio0.channel='auto'
set wireless.radio0.country='CN'

# Wireless default settings for radio1
set wireless.default_radio1.wnm_sleep_mode='1'
set wireless.default_radio1.ieee80211k='1'
set wireless.default_radio1.time_advertisement='2'
set wireless.default_radio1.bss_transition='1'
set wireless.default_radio1.proxy_arp='1'

# Wireless radio1 specific settings
set wireless.radio1.htmode='HE40'
set wireless.radio1.channel='auto'
set wireless.radio1.country='CN'

# Network settings
set network.@device[0].packet_steering='0'
set network.@device[0].igmp_snooping='1'
set network.@device[0].multicast_querier='1'
set network.@device[0].flow_offloading='0'
set network.@device[0].flow_offloading_hw='0'

# uHTTPd settings
set uhttpd.main.redirect_https='1'

EOF

uci commit system
uci commit wireless
uci commit network
uci commit uhttpd

exit 0
